name: f4-prices-pipeline

networks:
  redpanda-network:
    name: redpanda-network
    driver: bridge
    

#Yaml anchor for shared variables
x-shared-environment: &shared-env
  MODE: "historical"
  PROJECT_NAME: "ml_system_c1"
  FEATURE_GROUP_FORM4_BASIC: "form4sd"
  FEATURE_GROUP_TARGET: "target_90_disposed"
  FEATURE_GROUP_OFFSET_TARGET: "target_90_disposed_offset"
  FEATURE_GROUP_AVG: "avg_90_disposed"
  FEATURE_GROUP_OFFSET_AVG: "avg_90_disposed_offset"
  FEATURE_GROUP_PRICES: "prices"
  FEATURE_GROUP_VERSION: 1
  EVENT_TIME: "date"
  DELTA_PERIOD: 90
  BUFFER_SIZE: 100
  OFFSET_BUFFER_SIZE: 100
  MATERIALIZATION_BATCH_SIZE: 100
  DELAY: 15
  

services:
  yahoo-connect:
    build:
      context: ../prices-feature-pipeline/yahoo_connect
    networks:
      - redpanda-network
    env_file:
      - ../prices-feature-pipeline/yahoo_connect/.env
      - ../prices-feature-pipeline/yahoo_connect/.credentials.env
    environment:
      <<: *shared-env
    ports:
      - "8011:8011"
    restart: always
'''
  target:
    build:
      context: ../prices-feature-pipeline/target
    networks:
      - redpanda-network
    env_file:
      - ../prices-feature-pipeline/target/.env
      - ../prices-feature-pipeline/target/.credentials.env
    environment:
      <<: *shared-env
    ports:
      - "8012:8012"
    restart: always
   

  avg-target:
    build:
      context: ../prices-feature-pipeline/avg-target
    networks:
      - redpanda-network
    env_file:
      - ../prices-feature-pipeline/avg-target/.env
      - ../prices-feature-pipeline/avg-target/.credentials.env
    environment:
      <<: *shared-env
    ports:
      - "8013:8013"
    restart: always
    
'''