name: f4-feature-pipeline

networks:
  redpanda-network:
    name: redpanda-network
    driver: bridge
    

#Yaml anchor for shared variables
x-shared-environment: &shared-env
  KAFKA_BROKER_ADDRESS: "redpanda-0:9092"
  AUTO_OFFSET_RESET: "earliest"
  MODE: "historical"
  PROJECT_NAME: "ml_system_c1"
  POLL_TIMEOUT: 30
  YEARS: 5
  FORM_TYPE: 4
  TEST_TRIAL: "False"
  TEST_SIZE: 1000
  BUFFER_SIZE: 500
  SLEEP_TIME: 0.1
  DELAY: 90
  API_DROP: "exchange"

services:
  scraper:
    build:
      context: ../sec-feature-pipeline/scraper
    networks:
      - redpanda-network
    env_file:
      - ../sec-feature-pipeline/scraper/.env
    environment:
      <<: *shared-env
    ports:
      - "8010:8010"
    restart:
      "on-failure:5"

  api-enricher:
    build:
      context: ../sec-feature-pipeline/api-enricher
    networks:
      - redpanda-network
    env_file:
      - ../sec-feature-pipeline/api-enricher/.env
    environment:
      <<: *shared-env
    ports:
      - "8009:8009"
    restart:
      "on-failure:5"
    depends_on:
      - scraper

  kafka-to-store:
    build:
      context: ../sec-feature-pipeline/kafka-to-store
    networks:
      - redpanda-network
    env_file:
      - ../sec-feature-pipeline/kafka-to-store/.credentials.env
      - ../sec-feature-pipeline/kafka-to-store/.env
    environment:
      <<: *shared-env
    ports:
      - "8008:8008"
    restart:
      "on-failure:5"

    depends_on:
      - api-enricher