name: training-feature-pipeline

networks:
  redpanda-network:
    name: redpanda-network
    driver: bridge

# Yaml anchor for shared variables
x-shared-environment: &shared-env
  SHARED_ENV_VAR1: value1

services:
  master-index:
    build:
      context: ../..
      dockerfile: sec-feature-pipeline/master-index/Dockerfile
    networks:
      - redpanda-network
    env_file:
      - training-master.env
    environment:
      <<: *shared-env
    ports:
      - "9000:9000"
    restart:
      "on-failure:5"
    profiles:
      - sec

  scraper:
    build:
      context: ../..
      dockerfile: sec-feature-pipeline/scraper/Dockerfile
    networks:
      - redpanda-network
    env_file:
      - training-scraper.env
    environment:
      <<: *shared-env
    ports:
      - "9001:9001"
    restart:
      "on-failure:5"
    depends_on:
       - master-index
    profiles:
      - sec
 

  kafka-to-store:
    build:
      context: ../..
      dockerfile: sec-feature-pipeline/kafka-to-store/Dockerfile
    networks:
      - redpanda-network
    env_file:
      - .credentials.env
      - training-feature.env
      - .env
    environment:
      <<: *shared-env
    ports:
      - "9002:9002"
    restart:
      "on-failure:5"
    depends_on:
      - scraper
    profiles:
      - sec

  yahoo-connect:
    build:
      context: ../..
      dockerfile: prices-feature-pipeline/yahoo_connect/Dockerfile
    networks:
      - redpanda-network
    env_file:
      - training-yahoo.env
      - .credentials.env
    environment:
      <<: *shared-env
    ports:
      - "9003:9003"
    restart:
      "on-failure:5"
    #profiles:
    #  - prices

  target:
    build:
      context: ../..
      dockerfile: prices-feature-pipeline/target/Dockerfile
    networks:
      - redpanda-network
    env_file:
      - training-target.env
      - .credentials.env
    environment:
      <<: *shared-env
    ports:
      - "9005:9005"
    restart:
      "on-failure:5"
    depends_on:
      - yahoo-connect
    profiles:
      - prices